
import frappe
from frappe import _
from frappe.utils import flt, getdate


def execute(filters=None):
    filters = frappe._dict(filters or {})
    return get_columns(), get_data(filters)


# =====================================================================
# COLUMNS
# =====================================================================

def get_columns():
    columns = [
        ("EWB No", "ewb_no", "Data", 145),
        ("EWB Date", "ewb_date", "Datetime", 155),
        ("Supply Type", "supply_type", "Data", 100),
        ("Sub Supply Type", "sub_supply_type", "Data", 130),
        ("Doc No", "doc_no", "Data", 160),
        ("Doc Date", "doc_date", "Date", 110),
        ("Doc Type", "doc_type", "Data", 110),
        ("Generated By", "generated_by", "Data", 150),
        ("From GSTIN", "from_gstin", "Data", 155),
        ("From Trader Name", "from_trader_name", "Data", 220),
        ("From Address", "from_address", "Data", 220),
        ("From Place", "from_place", "Data", 145),
        ("From Pincode", "from_pincode", "Data", 100),
        ("To GSTIN", "to_gstin", "Data", 155),
        ("To Trader Name", "to_trader_name", "Data", 220),
        ("To Address", "to_address", "Data", 220),
        ("To Place", "to_place", "Data", 145),
        ("To Pincode", "to_pincode", "Data", 100),
        # ("Other Party GSTIN", "other_party_gstin", "Data", 155),
        ("Status", "status", "Data", 100),
        ("No of Items", "no_of_items", "Int", 95),
        ("Main HSN Code", "main_hsn_code", "Data", 120),
        ("HSN Desc", "hsn_desc", "Data", 200),
        ("Assessable Value", "assessable_value", "Currency", 135),
        ("SGST Value", "sgst_value", "Currency", 115),
        ("CGST Value", "cgst_value", "Currency", 115),
        ("IGST Value", "igst_value", "Currency", 115),
        ("CESS Value", "cess_value", "Currency", 110),
        ("CESS Non.Advol Value", "cess_non_advol_value", "Currency", 150),
        ("Other Value", "other_value", "Currency", 110),
        ("Total Inv.Value", "total_invvalue", "Currency", 140),
        ("Valid Till Date", "valid_till_date", "Date", 120),
        ("Mode of GEN.", "mode_of_gen", "Data", 100),
        ("IRN", "irn", "Data", 180),
        ("Source", "source", "Data", 160),

        # ERPNext linked document details
        ("Gate In No", "gate_in_no", "Data", 150),
        ("Gate In Date", "gate_in_date", "Date", 110),
        ("Gate In Time", "gate_in_time", "Data", 100),
        ("Logistic In No.", "logistic_in_no", "Data", 150),
        ("Logistic In Dt.", "logistic_in_date", "Date", 110),
        ("Logistic In Time", "logistic_in_time", "Data", 100),
        ("GRC/PRC No.", "grc_prc_no", "Data", 150),
        ("GRC/PRC Date", "grc_prc_date", "Date", 110),
        ("GRC/PRC Time", "grc_prc_time", "Data", 100),
        (
            "Purchase Invoice/Sales Return No.",
            "purchase_invoice_sales_return_no",
            "Data",
            220,
        ),
        (
            "Purchase Invoice/Sales Return Dt.",
            "purchase_invoice_sales_return_date",
            "Data",
            180,
        ),
        (
            "Purchase Invoice/Sales Return Time",
            "purchase_invoice_sales_return_time",
            "Data",
            180,
        ),
    ]

    return [
        {
            "label": _(label),
            "fieldname": fieldname,
            "fieldtype": fieldtype,
            "width": width,
        }
        for label, fieldname, fieldtype, width in columns
    ]


# =====================================================================
# MAIN DATA - READ FROM ADVANCE E-WAYBILL LOG
# =====================================================================

def get_data(filters):
    fields = [
        "name",
        "ewb_no",
        "ewb_date",
        "supply_type",
        "sub_supply_type",
        "doc_no",
        "doc_date",
        "doc_type",
        "generated_by",
        "from_gstin",
        "from_trader_name",
        "from_address",
        "from_place",
        "from_pincode",
        "to_gstin",
        "to_trader_name",
        "to_address",
        "to_place",
        "to_pincode",
        "status",
        "no_of_items",
        "main_hsn_code",
        "hsn_desc",
        "assessable_value",
        "sgst_value",
        "cgst_value",
        "igst_value",
        "cess_value",
        "cess_non_advol_value",
        "other_value",
        "total_invvalue",
        "valid_till_date",
        "mode_of_gen",
        "irn",
        "source",
    ]

    logs = frappe.get_all(
        "Advance e-Waybill Log",
        fields=fields,
        order_by="ewb_date desc",
    )

    result = []

    for log in logs:
        ewb_no = log.ewb_no or ""

        ewb_date = log.ewb_date
        doc_date = log.doc_date

        # -------------------------------------------------------------
        # FILTER: EWB NO
        # Existing filter fieldname: eway_bill_no
        # -------------------------------------------------------------

        filter_ewb_no = filters.get("eway_bill_no")

        if filter_ewb_no:
            if str(filter_ewb_no).strip().lower() not in str(ewb_no).lower():
                continue

        # -------------------------------------------------------------
        # FILTER: EWB DATE
        # Existing filter fieldname: eway_bill_date
        # -------------------------------------------------------------

        filter_date = filters.get("eway_bill_date")

        if filter_date:
            if not ewb_date:
                continue

            if getdate(ewb_date) != getdate(filter_date):
                continue

        # -------------------------------------------------------------
        # FILTER: DOC TYPE
        # -------------------------------------------------------------

        filter_doc_type = filters.get("doc_type")

        if filter_doc_type:
            if str(filter_doc_type).strip().lower() not in (
                str(log.doc_type or "").strip().lower(),
                get_document_type_label(log.doc_type).strip().lower(),
            ):
                continue

        # -------------------------------------------------------------
        # FILTER: DOC NO
        # -------------------------------------------------------------

        filter_doc_no = filters.get("doc_no")

        if filter_doc_no:
            if str(filter_doc_no).strip().lower() not in str(log.doc_no or "").lower():
                continue

        # -------------------------------------------------------------
        # OTHER PARTY GSTIN
        #
        # Inward: supplier/from party
        # Outward: recipient/to party
        # -------------------------------------------------------------

        supply_type = str(log.supply_type or "").strip().lower()

        if supply_type in ("inward", "i"):
            other_party_gstin = log.from_gstin or ""
        elif supply_type in ("outward", "o"):
            other_party_gstin = log.to_gstin or ""
        else:
            other_party_gstin = ""

        # -------------------------------------------------------------
        # ERP DOCUMENT CHAIN
        #
        # Advance e-Waybill Log does not have reference_doctype or
        # reference_name. Therefore, try to identify the ERP document
        # by matching Doc No against known ERPNext document names.
        # -------------------------------------------------------------

        erp_details = get_linked_document_details(
            log.doc_no,
            log.ewb_no,
        )

        result.append({
            "ewb_no": ewb_no,
            "ewb_date": ewb_date,
            "supply_type": log.supply_type,
            "sub_supply_type": log.sub_supply_type,
            "doc_no": log.doc_no,
            "doc_date": doc_date,
            "doc_type": get_document_type_label(log.doc_type),
            "generated_by": log.generated_by,
            "from_gstin": log.from_gstin,
            "from_trader_name": log.from_trader_name,
            "from_address": log.from_address,
            "from_place": log.from_place,
            "from_pincode": log.from_pincode,
            "to_gstin": log.to_gstin,
            "to_trader_name": log.to_trader_name,
            "to_address": log.to_address,
            "to_place": log.to_place,
            "to_pincode": log.to_pincode,
            "other_party_gstin": other_party_gstin,
            "status": log.status,
            "no_of_items": log.no_of_items,
            "main_hsn_code": log.main_hsn_code,
            "hsn_desc": log.hsn_desc,
            "assessable_value": flt(log.assessable_value),
            "sgst_value": flt(log.sgst_value),
            "cgst_value": flt(log.cgst_value),
            "igst_value": flt(log.igst_value),
            "cess_value": flt(log.cess_value),
            "cess_non_advol_value": flt(log.cess_non_advol_value),
            "other_value": flt(log.other_value),
            "total_invvalue": flt(log.total_invvalue),
            "valid_till_date": log.valid_till_date,
            "mode_of_gen": log.mode_of_gen,
            "irn": log.irn,
            "source": log.source,

            "gate_in_no": erp_details["gate_in_no"],
            "gate_in_date": erp_details["gate_in_date"],
            "gate_in_time": erp_details["gate_in_time"],
            "logistic_in_no": erp_details["logistic_in_no"],
            "logistic_in_date": erp_details["logistic_in_date"],
            "logistic_in_time": erp_details["logistic_in_time"],
            "grc_prc_no": erp_details["grc_prc_no"],
            "grc_prc_date": erp_details["grc_prc_date"],
            "grc_prc_time": erp_details["grc_prc_time"],
            "purchase_invoice_sales_return_no":
                erp_details["purchase_invoice_sales_return_no"],
            "purchase_invoice_sales_return_date":
                erp_details["purchase_invoice_sales_return_date"],
            "purchase_invoice_sales_return_time":
                erp_details["purchase_invoice_sales_return_time"],
        })

    return result


# =====================================================================
# DOCUMENT TYPE LABEL
# =====================================================================

def get_document_type_label(doc_type):
    mapping = {
        "INV": "Invoice",
        "BIL": "Bill",
        "BOE": "Bill of Entry",
        "CHL": "Challan",
        "BOL": "Bill of Lading",
        "OTH": "Others",
        "CNT": "Credit Note",
        "DLC": "Delivery Challan",
        "TAX": "Tax Invoice",
    }

    value = str(doc_type or "").strip()
    return mapping.get(value.upper(), value)


# =====================================================================
# ERP DOCUMENT LOOKUP
# =====================================================================

def get_erp_details_by_doc_no(doc_no):
    details = empty_erp_details()

    if not doc_no:
        return details

    # Match exact ERPNext document name.
    # The first match is used if a name exists in multiple DocTypes.
    candidates = [
        ("Purchase Receipt", get_from_purchase_receipt),
        ("Purchase Invoice", get_from_purchase_invoice),
        ("Sales Invoice", get_from_sales_invoice),
    ]

    for doctype, handler in candidates:
        if frappe.db.exists(doctype, doc_no):
            try:
                return handler(doc_no)
            except Exception:
                frappe.log_error(
                    title="Advance e-Waybill Log - ERP Lookup Error",
                    message=frappe.get_traceback(),
                )
                return details

    return details


# =====================================================================
# EMPTY ERP DETAILS
# =====================================================================

def empty_erp_details():
    return {
        "gate_in_no": "",
        "gate_in_date": None,
        "gate_in_time": None,
        "logistic_in_no": "",
        "logistic_in_date": None,
        "logistic_in_time": None,
        "grc_prc_no": "",
        "grc_prc_date": None,
        "grc_prc_time": None,
        "purchase_invoice_sales_return_no": "",
        "purchase_invoice_sales_return_date": "",
        "purchase_invoice_sales_return_time": "",
    }


# =====================================================================
# PURCHASE RECEIPT
# =====================================================================

def get_from_purchase_receipt(pr_name):
    details = empty_erp_details()

    pr = frappe.db.get_value(
        "Purchase Receipt",
        pr_name,
        [
            "name",
            "posting_date",
            "posting_time",
            "is_return",
            "return_against",
            "custom_gate_entry",
        ],
        as_dict=True,
    )

    if not pr:
        return details

    grc_pr = pr

    if pr.is_return and pr.return_against:
        original_pr = frappe.db.get_value(
            "Purchase Receipt",
            pr.return_against,
            [
                "name",
                "posting_date",
                "posting_time",
                "custom_gate_entry",
            ],
            as_dict=True,
        )

        if original_pr:
            grc_pr = original_pr

    details["grc_prc_no"] = grc_pr.name
    details["grc_prc_date"] = grc_pr.posting_date
    details["grc_prc_time"] = time_value(grc_pr.posting_time)

    gate_entry = (
        getattr(pr, "custom_gate_entry", None)
        or getattr(grc_pr, "custom_gate_entry", None)
    )

    if gate_entry:
        add_gate_entry_details(details, gate_entry)

    add_purchase_invoice_details(details, grc_pr.name)

    return details


# =====================================================================
# PURCHASE INVOICE
# =====================================================================

def get_from_purchase_invoice(pi_name):
    details = empty_erp_details()

    pi = frappe.db.get_value(
        "Purchase Invoice",
        pi_name,
        [
            "name",
            "posting_date",
            "posting_time",
            "is_return",
            "return_against",
            "custom_gate_entry_",
        ],
        as_dict=True,
    )

    if not pi:
        return details

    details["purchase_invoice_sales_return_no"] = pi.name
    details["purchase_invoice_sales_return_date"] = str(pi.posting_date or "")
    details["purchase_invoice_sales_return_time"] = time_value(pi.posting_time)

    gate_entry = getattr(pi, "custom_gate_entry_", None)

    if gate_entry:
        add_gate_entry_details(details, gate_entry)

    pr_names = frappe.get_all(
        "Purchase Invoice Item",
        filters={
            "parent": pi_name,
            "purchase_receipt": ["is", "set"],
        },
        pluck="purchase_receipt",
        order_by="idx asc",
    )

    for pr_name in unique_values(pr_names):
        pr = frappe.db.get_value(
            "Purchase Receipt",
            pr_name,
            [
                "name",
                "posting_date",
                "posting_time",
                "is_return",
                "return_against",
                "custom_gate_entry",
            ],
            as_dict=True,
        )

        if not pr:
            continue

        original_pr = pr

        if pr.is_return and pr.return_against:
            original_pr = frappe.db.get_value(
                "Purchase Receipt",
                pr.return_against,
                [
                    "name",
                    "posting_date",
                    "posting_time",
                    "custom_gate_entry",
                ],
                as_dict=True,
            ) or pr

        details["grc_prc_no"] = original_pr.name
        details["grc_prc_date"] = original_pr.posting_date
        details["grc_prc_time"] = time_value(original_pr.posting_time)

        gate_entry = (
            getattr(original_pr, "custom_gate_entry", None)
            or gate_entry
        )

        if gate_entry:
            add_gate_entry_details(details, gate_entry)

        break

    return details


# =====================================================================
# SALES INVOICE
# =====================================================================

def get_from_sales_invoice(si_name):
    details = empty_erp_details()

    si = frappe.db.get_value(
        "Sales Invoice",
        si_name,
        [
            "name",
            "posting_date",
            "posting_time",
            "is_return",
            "return_against",
            "custom_gate_entry",
            "custom_outgoing_logistics_reference",
            "custom_outgoing_logistics_no",
        ],
        as_dict=True,
    )

    if not si:
        return details

    if si.is_return:
        details["purchase_invoice_sales_return_no"] = si.name
        details["purchase_invoice_sales_return_date"] = str(si.posting_date or "")
        details["purchase_invoice_sales_return_time"] = time_value(si.posting_time)

    if si.custom_gate_entry:
        add_gate_entry_details(details, si.custom_gate_entry)

    outgoing_logistics = (
        si.custom_outgoing_logistics_reference
        or si.custom_outgoing_logistics_no
    )

    if outgoing_logistics:
        add_sales_returns_from_outgoing_logistics(
            details,
            outgoing_logistics,
        )

    if not si.is_return:
        add_sales_returns_against_sales_invoice(details, si_name)

    return details


# =====================================================================
# GATE ENTRY
# =====================================================================

def add_gate_entry_details(details, gate_entry_name):
    gate = frappe.db.get_value(
        "Gate Entry",
        gate_entry_name,
        [
            "name",
            "date",
            "creation",
            "incoming_logistics",
        ],
        as_dict=True,
    )

    if not gate:
        return

    details["gate_in_no"] = gate.name
    details["gate_in_date"] = gate.date or (
        gate.creation.date() if gate.creation else None
    )
    details["gate_in_time"] = (
        gate.creation.time() if gate.creation else None
    )

    if gate.incoming_logistics:
        add_incoming_logistics_details(
            details,
            gate.incoming_logistics,
        )


# =====================================================================
# INCOMING LOGISTICS
# =====================================================================

def add_incoming_logistics_details(details, logistics_name):
    il = frappe.db.get_value(
        "Incoming Logistics",
        logistics_name,
        ["name", "date", "creation"],
        as_dict=True,
    )

    if not il:
        return

    details["logistic_in_no"] = il.name
    details["logistic_in_date"] = il.date or (
        il.creation.date() if il.creation else None
    )
    details["logistic_in_time"] = (
        il.creation.time() if il.creation else None
    )


# =====================================================================
# PURCHASE INVOICE FROM PURCHASE RECEIPT
# =====================================================================

def add_purchase_invoice_details(details, pr_name):
    items = frappe.get_all(
        "Purchase Invoice Item",
        filters={"purchase_receipt": pr_name},
        fields=["parent"],
        order_by="parent asc",
    )

    names = unique_values([row.parent for row in items])

    if not names:
        return

    documents = frappe.get_all(
        "Purchase Invoice",
        filters={
            "name": ["in", names],
            "docstatus": 1,
        },
        fields=[
            "name",
            "posting_date",
            "posting_time",
            "is_return",
        ],
        order_by="posting_date asc, posting_time asc",
    )

    append_transaction_details(details, documents)


# =====================================================================
# SALES RETURNS AGAINST SALES INVOICE
# =====================================================================

def add_sales_returns_against_sales_invoice(details, sales_invoice):
    returns = frappe.get_all(
        "Sales Invoice",
        filters={
            "return_against": sales_invoice,
            "is_return": 1,
            "docstatus": 1,
        },
        fields=[
            "name",
            "posting_date",
            "posting_time",
            "is_return",
        ],
        order_by="posting_date asc, posting_time asc",
    )

    append_transaction_details(details, returns)


# =====================================================================
# SALES RETURNS FROM OUTGOING LOGISTICS
# =====================================================================

def add_sales_returns_from_outgoing_logistics(details, outgoing_logistics):
    returns = frappe.get_all(
        "Sales Invoice",
        filters={
            "custom_outgoing_logistics_reference": outgoing_logistics,
            "is_return": 1,
            "docstatus": 1,
        },
        fields=[
            "name",
            "posting_date",
            "posting_time",
            "is_return",
        ],
        order_by="posting_date asc, posting_time asc",
    )

    append_transaction_details(details, returns)


# =====================================================================
# APPEND PI / SALES RETURN DETAILS
# =====================================================================

def append_transaction_details(details, documents):
    if not documents:
        return

    unique_documents = []
    seen = set()

    for doc in documents:
        if doc.name in seen:
            continue
        seen.add(doc.name)
        unique_documents.append(doc)

    # Document numbers
    key = "purchase_invoice_sales_return_no"
    existing = [
        value.strip()
        for value in str(details[key] or "").split(",")
        if value.strip()
    ]

    for doc in unique_documents:
        if doc.name not in existing:
            existing.append(doc.name)

    details[key] = ", ".join(existing)

    # Document dates
    key = "purchase_invoice_sales_return_date"
    existing = [
        value.strip()
        for value in str(details[key] or "").split(",")
        if value.strip()
    ]

    for doc in unique_documents:
        if not doc.posting_date:
            continue

        value = str(doc.posting_date)
        if value not in existing:
            existing.append(value)

    details[key] = ", ".join(existing)

    # Document times
    key = "purchase_invoice_sales_return_time"
    existing = [
        value.strip()
        for value in str(details[key] or "").split(",")
        if value.strip()
    ]

    for doc in unique_documents:
        value = time_value(doc.posting_time)
        if value and value not in existing:
            existing.append(value)

    details[key] = ", ".join(existing)


# =====================================================================
# UTILITIES
# =====================================================================

def unique_values(values):
    result = []
    seen = set()

    for value in values:
        if not value or value in seen:
            continue

        seen.add(value)
        result.append(value)

    return result

def time_value(value):
    if value is None:
        return ""

    try:
        if hasattr(value, "total_seconds"):
            total_seconds = int(value.total_seconds())
            hours = total_seconds // 3600
            minutes = (total_seconds % 3600) // 60
            seconds = total_seconds % 60

            return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

        return str(value)

    except Exception:
        return str(value)
    
    

def get_linked_document_details(doc_no, ewb_no=None):
    details = empty_erp_details()

    if not doc_no and not ewb_no:
        return details

    # 1. Find Gate Entry using E-Way Bill Doc No
    gate_entry = None

    if doc_no:
        gate_entry = frappe.db.get_value(
            "Gate Entry",
            {"document_nos": ["like", f"%{doc_no}%"]},
            ["name", "document_date", "incoming_logistics"],
            as_dict=True,
            order_by="creation desc",
        )

    # 2. Find Incoming Logistics:
    # First match E-Way Bill No, then fallback to Doc No
    logistics = None

    if ewb_no and frappe.db.exists("Incoming Logistics", {"invoice_no": ewb_no}):
        logistics = frappe.db.get_value(
            "Incoming Logistics",
            {"invoice_no": ewb_no},
            ["name", "invoice_date", "invoice_time", "gate_entry_no"],
            as_dict=True,
            order_by="creation desc",
        )

    if not logistics and doc_no:
        logistics = frappe.db.get_value(
            "Incoming Logistics",
            {"invoice_no": doc_no},
            ["name", "invoice_date", "invoice_time", "gate_entry_no"],
            as_dict=True,
            order_by="creation desc",
        )

    # 3. Get Incoming Logistics details and linked Gate Entry
    if logistics:
        details["logistic_in_no"] = logistics.name
        details["logistic_in_date"] = logistics.invoice_date
        details["logistic_in_time"] = str(logistics.invoice_time or "")

        # Prefer Gate Entry linked from Incoming Logistics
        if logistics.gate_entry_no and frappe.db.exists(
            "Gate Entry", logistics.gate_entry_no
        ):
            gate_entry = frappe.db.get_value(
                "Gate Entry",
                logistics.gate_entry_no,
                ["name", "posting_date", "posting_time"],
                as_dict=True,
            )

            if gate_entry:
                details["gate_in_no"] = gate_entry.name
                details["gate_in_date"] = gate_entry.posting_date
                details["gate_in_time"] = str(gate_entry.posting_time or "")

    # Fallback: use Gate Entry found through document_nos
    if gate_entry and not details.get("gate_in_no"):
        details["gate_in_no"] = gate_entry.name
        details["gate_in_date"] = (
            gate_entry.get("posting_date")
            or gate_entry.get("document_date")
        )
        details["gate_in_time"] = str(
            gate_entry.get("posting_time") or ""
        )

    # 4. Purchase Receipt through Purchase Receipt Item.custom_bulk_gate_entry
    gate_entry_name = details.get("gate_in_no")

    if gate_entry_name and frappe.db.has_column(
        "Purchase Receipt Item", "custom_bulk_gate_entry"
    ):
        pr_items = frappe.get_all(
            "Purchase Receipt Item",
            filters={"custom_bulk_gate_entry": gate_entry_name},
            fields=["parent"],
            order_by="parent desc",
        )

        pr_names = unique_values([row.parent for row in pr_items])

        if pr_names:
            pr = frappe.db.get_value(
                "Purchase Receipt",
                {
                    "name": ["in", pr_names],
                    "docstatus": ["!=", 2],
                },
                ["name", "posting_date", "posting_time"],
                as_dict=True,
                order_by="posting_date desc, posting_time desc",
            )

            if pr:
                details["grc_prc_no"] = pr.name
                details["grc_prc_date"] = pr.posting_date
                details["grc_prc_time"] = str(pr.posting_time or "")

                # Purchase Invoice linked to this Purchase Receipt
                add_purchase_invoice_details(details, pr.name)

    # 5. If Doc No itself is an ERP document, use its relationships
    if doc_no and frappe.db.exists("Purchase Invoice", doc_no):
        pi_details = get_from_purchase_invoice(doc_no)

        for key in (
            "purchase_invoice_sales_return_no",
            "purchase_invoice_sales_return_date",
            "purchase_invoice_sales_return_time",
        ):
            if pi_details.get(key):
                details[key] = pi_details[key]

    elif doc_no and frappe.db.exists("Sales Invoice", doc_no):
        si_details = get_from_sales_invoice(doc_no)

        for key in (
            "purchase_invoice_sales_return_no",
            "purchase_invoice_sales_return_date",
            "purchase_invoice_sales_return_time",
        ):
            if si_details.get(key):
                details[key] = si_details[key]

    return details